[project]
name = "discord-bot"
version = "0.1.0"
description = ""
authors = ["anemoneruri <example@example.com>"]
requires-python = ">=3.11"
dependencies = [
    "discord-py",
    "feedparser>=6.0.12",
]
